nbame: Pyth SDK

on:
  push:
    branches: [ main ]
    paths: [ pyth-sdk/** ]
  pull_request:
    branches: [ main ]
    paths: [ pyth-sdk/** ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pyth-sdk
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libudev-dev
    - name: Build
      run: cargo +1.69.0 build --verbose
    - name: Run tests
      run: cargo +1.69.0 test --verbose
  schema-check:
    name: Check schema changes are committed
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pyth-sdk
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Generate Schema
        run: cargo +1.69.0 run --example schema

      - name: Schema Changes
        # fails if any changes not committed
        run: git diff --exit-code schema
