name: Solana SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pyth-sdk-solana
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libudev-dev
    - name: Build
      run: cargo +1.69.0 build --verbose
    - name: Run tests
      run: cargo +1.69.0 test --verbose
  test-contract:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pyth-sdk-solana/test-contract
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libudev-dev
    - name: Install Solana Binaries
      run: |
        # Installing 1.17.x cli tools to have sbf instead of bpf. bpf does not work anymore.
        sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    - name: Build
      run: cargo +1.69.0 build --verbose
    - name: Run tests
      run: cargo +1.69.0 test --verbose
    - name: Build BPF
      run: cargo +1.69.0 build-bpf --verbose
    - name: Run BPF tests
      run: cargo +1.69.0 test-bpf --verbose
